version: "3.9"

services:
  motorshop_api:
    container_name: "motorshop_api"
    build: .
    image: motorshop_api
    networks:
      - motorshop_m6_project
    env_file:
      - .env
    ports:
      - $PORT:$PORT
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      docker_db:
        condition: service_healthy
    command: bash -c "yarn typeorm migration:run -d src/data-source && yarn dev"

  docker_db:
    container_name: motorshop_db
    image: postgres:14
    networks:
      - motorshop_m6_project
    env_file:
      - .env
    ports:
      - $PGPORT:$PGPORT
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username=$POSTGRES_USER --dbname=$POSTGRES_DB",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  motorshop_m6_project:
    driver: bridge
